[versions]
java = "25"
kotlin = "2.3.0"

serializationJson = "1.9.0"

kotest = "5.9.1"
mockk  = "1.13.14"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

[libraries]
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serializationJson" }

kotest-runner     = { module = "io.kotest:kotest-runner-junit5",   version.ref = "kotest" }
kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-property   = { module = "io.kotest:kotest-property",        version.ref = "kotest" }
mockk             = { module = "io.mockk:mockk",                   version.ref = "mockk" }
[bundles]
testing = ["kotest-runner", "kotest-assertions", "kotest-property", "mockk"]